namespace STCAPI.Model.QVD
{
    public class B2CSumaryReportModel
    {
        public string BATCH_ID { get; set; }
        public string DATA_FIELD { get; set; }
        public string REVENUE_MNY { get; set; }
        public string REVERSAL_FLAG { get; set; }
        public string QUANTITY { get; set; }
        public string JURISDICTION { get; set; }
        public string PEAK_OFF_PEAK_FLAG { get; set; }
        public string SERVICE_TYPE { get; set; }
        public string PRODUCT_ID { get; set; }
        public string DISC_USAGE_TYPE { get; set; }
        public string BILL_CYCLE { get; set; }
        public string DISTRICT { get; set; }
        public string CUSTOMER_TYPE { get; set; }
        public string CUSTOMER_SUBTYPE { get; set; }
        public string INDUSTRY_TYPE { get; set; }
        public string INDUSTRY_NAME { get; set; }
        public string GL_REV_CODE_NAME { get; set; }
        public string ABC_REV_CODE_NAME { get; set; }
        public string SP_NAME { get; set; }
        public string SP_PERCENTAGE { get; set; }
        public string SP_ADJUSTMENT_TYPE { get; set; }
        public string SP_REVENUE_CODE_NAME { get; set; }
        public string REVENUE_CODE_ID { get; set; }
        public string REVENUE_CODE_NAME { get; set; }
        public string SERVICE_CODE { get; set; }
        public string EVENT_TYPE { get; set; }
        public string USAGE_TYPE { get; set; }
        public string USAGE_TYPE_DESC { get; set; }
        public string IRB_PRICE_PLAN { get; set; }
        public string CALL_CATEGORY { get; set; }
        public string DESTINATION { get; set; }
        public string VPLMN { get; set; }
        public string PRODUCT_NAME { get; set; }
        public string CHARGE_TYPE { get; set; }
        public string ADJUSTMENT_TYPE { get; set; }
        public string ADJUSTMENT_NAME { get; set; }
        public string DISCOUNT_NAME { get; set; }
        public string DISCOUNT_TYPE { get; set; }
        public string DISCOUNT_CLASS { get; set; }
        public string PERIOD { get; set; }
        public string CREATION_DATE { get; set; }
        public string STC_SHARE { get; set; }
        public string SP_ACCOUNT_NUM { get; set; }
        public string REV_SHARE_FLAG { get; set; }
        public string BILL_DATE { get; set; }
        public string BATCH_REC_SEQ { get; set; }
        public string CUSTOMER_SEGMENT { get; set; }
        public string CUSTOMER_VALUE { get; set; }
        public string RELATED_PARTY { get; set; }
        public string SOURCE_SYSTEM { get; set; }
        public string ORG_CUSTOMER_SEGMENT { get; set; }
        public string FILE_NAME { get; set; }
        public string XCREATION_DATE { get; set; }
        public string CREATED_BY { get; set; }
        public string LAST_UPDATED_DATE { get; set; }
        public string LAST_UPDATED_BY { get; set; }
        public string LAST_UPDATED_LOGIN { get; set; }
        public string STATUS { get; set; }
        public string CEXCEPTION { get; set; }
        public string DIST_LINE_ID { get; set; }
        public string LINE_ID { get; set; }
        public string CUST_INDUST { get; set; }
        public string GLREV_DATAFE { get; set; }
        public string NEGATIVE_REV_MNY { get; set; }
        public string REQUEST_ID { get; set; }
        public string CURRENCY_CODE { get; set; }
        public string CONVERSION_RATE_TYPE { get; set; }
        public string CONVERSION_RATE_VALUE { get; set; }
        public string CONVERSION_DATE { get; set; }
        public string ACCOUNTING_DATE { get; set; }
        public string SECOND_IDENTIFIER { get; set; }
        public string DISCOUNT { get; set; }
        public string DISCOUNT_PCT { get; set; }
        public string EVENT_ID { get; set; }
        public string JOURNAL_HEADER_DESC { get; set; }
        public string THIRD_IDENTIFIER { get; set; }
        public string ARCHIVE { get; set; }
        public string MAP_CUST_EXCEPTION { get; set; }
        public string MAP_CUST_EXP_SEGMENT { get; set; }
        public string ACCOUNT_DRIVER { get; set; }
        public string COMPANY { get; set; }
        public string CUSTOMER_DRIVER { get; set; }
        public string CATEGORY { get; set; }
        public string ERROR_GRP { get; set; }
        public string ERROR_MESSAGE { get; set; }
        public string ACCOUNT_MAP_SEGMENT { get; set; }
        public string EVENT_GROUP_ID { get; set; }
        public string CUST_CCID { get; set; }
        public string CUSTOMER_DRIVER_ARCHIVE { get; set; }
        public string CUSTOMER_SEGMENT_ARCHIVE { get; set; }
        public string DISTRICT_DRIVER { get; set; }
        public string ACCOUNT_MAP_SEGMENT_EXP { get; set; }
        public string ARCV { get; set; }
        public string ACCOUNT_ARCHIVE { get; set; }
        public string ACC { get; set; }
        public string INPUT_VALUE_CONSTANT { get; set; }
        public string CUST_EXP_INPUT_VALUE { get; set; }
        public string CUST_EXP_OUTPUT_VALUE { get; set; }
        public string MAPPING_SET_CODE { get; set; }
        public string ARCHIVE_FLAG { get; set; }
        public string ACCOUNTING_STATUS { get; set; }
        public string LINE_NUMBER { get; set; }
        public string FIRST_DISTRIBUTION_IDENTIFIER { get; set; }
        public string GL_REF { get; set; }
        public string INDUSTRY_DRIVER { get; set; }
        public string INDUSTRY_DRIVER_ARCHIVE { get; set; }
        public string INDS_EXP_INPUT_VALUE { get; set; }
        public string INDS_EXP_OUTPUT_VALUE { get; set; }
        public string INDS_MAPPING_SET_CODE { get; set; }
        public string TAX_CODE { get; set; }
        public string TAX_RATE { get; set; }
        public string IFRS_BILLED_REV_PK { get; set; }
        public string PercentageKey { get; set; }
        public string Table { get; set; }

    }
}
